name: Publish to Test Pypi

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.9
        with:
          python_version: 3.6
          repository_name: "test-pypi"
          repository_url: "https://test.pypi.org/legacy/"
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          ignore_dev_requirements: "yes"
